# Generated by Django 4.1.4 on 2023-09-02 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysiteapp', '0002_upload_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload_item',
            name='u_image',
            field=models.FileField(default='', null=True, upload_to='images/'),
        ),
    ]
